# Generated by Django 4.1 on 2022-08-22 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cpf', models.IntegerField(max_length=11)),
                ('data', models.DateField(auto_now_add=True)),
                ('celular', models.CharField(max_length=15)),
                ('telefone', models.CharField(max_length=15, null=True)),
                ('data_nasc', models.DateField()),
                ('tipo', models.CharField(choices=[('B', 'Basico'), ('P', 'Premium'), ('G', 'God')], default='B', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('uf', models.CharField(max_length=2)),
                ('numero', models.IntegerField(max_length=6, unique=True)),
                ('complemento', models.TextField()),
                ('cep', models.IntegerField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='hello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveSmallIntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.categoria')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_pagamento', models.CharField(choices=[('R', 'Recusado'), ('A', 'Aguardando'), ('C', 'Concluido')], default='A', max_length=1)),
                ('status_pedido', models.CharField(choices=[('CA', 'A caminho'), ('EN', 'Entregue ao usuario'), ('PR', 'preparando'), ('CAR', 'No carrinho'), ('CAN', 'pedido cancelado')], default='CAR', max_length=3)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tipo_pagamento', models.CharField(choices=[('P', 'Pix'), ('C', 'Cartao'), ('B', 'Boleto'), ('D', 'Dinheiro')], default='P', max_length=1)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.cliente')),
            ],
        ),
    ]
